sonar.projectKey=shifaurrehman_Noteo
sonar.organization=shifaurrehman
sonar.sources=src
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**, **/.expo/**, **/dist/**, **/assets/**
sonar.sourceEncoding=UTF-8
