sonar.projectKey=shifaurrehman_Ai-Note-Taker
sonar.organization=shifatech
sonar.sources=src
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**, **/.expo/**, **/dist/**, **/assets/**
sonar.sourceEncoding=UTF-8
