sonar.projectKey=shifaurrehman_Ai-Note-Taker
sonar.organization=shifatech
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/__tests__/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**, **/.expo/**, **/dist/**, **/assets/**
sonar.sourceEncoding=UTF-8
