name: EAS Preview Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: EAS Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node
        uses: actions/setup-node@6114389622d1591eda738166c433cce56f5c5b96 # v4.1.0
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup EAS
        uses: expo/expo-github-action@03e944f7b6b10dca0bbfa17acc28e9324a35041a # v8.1.1
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build Preview
        run: eas build --profile preview --platform all --non-interactive
